ALTER TABLE users
	ADD COLUMN IF NOT EXISTS password_change_required BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
	ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMP NULL;

ALTER TABLE users
	ADD COLUMN IF NOT EXISTS password_reset_at TIMESTAMP NULL;

ALTER TABLE users
	ADD COLUMN IF NOT EXISTS password_reset_by TEXT NOT NULL DEFAULT '';
