import {useEffect,useState} from "react";
import {DesktopAuditClient,desktopAuditClient,type DesktopAuditEvent,type DesktopTerminalSession} from "../api/desktopAudit";

const guidance:Record<string,string>={slow_consumer:"The viewer network or decoder could not keep up. Lower quality and retry.",hard_expired:"The eight-hour authorization expired. Start a new session.",idle_timeout:"The encrypted relay was idle. Retry the session.",rate_limit:"The relay traffic limit was exceeded. Lower quality and retry.",frame_limit:"The endpoint sent an oversized encrypted frame.",user_ended:"The operator ended the session.",agent_ended:"The endpoint ended the session.",local_ended:"A person at the endpoint ended the session.",screen_recording_required:"Grant Screen Recording on the remote Mac.",accessibility_required:"Grant Accessibility on the remote Mac for control.",session_conflict:"Another operator already has the device."};

export function DesktopSessionHistory({sessionID,client=desktopAuditClient}:{sessionID:string;client?:DesktopAuditClient}){
  const [events,setEvents]=useState<DesktopAuditEvent[]>([]),[after,setAfter]=useState(0),[error,setError]=useState("");
  const [sessions,setSessions]=useState<DesktopTerminalSession[]>([]),[sessionAfter,setSessionAfter]=useState(0),[historyError,setHistoryError]=useState("");
  async function load(){try{const result=await client.events(sessionID,after,50);setEvents(value=>[...value,...result.events]);setAfter(result.next_after_sequence);setError("")}catch{setError("Session history is temporarily unavailable.")}}
  async function loadTerminal(){if(typeof client.history!=="function")return;try{const result=await client.history(sessionAfter,25);setSessions(value=>[...value,...result.sessions]);setSessionAfter(result.next_after);setHistoryError("")}catch{setHistoryError("Terminal session history is temporarily unavailable.")}}
  useEffect(()=>{if(sessionID)void load();void loadTerminal()},[sessionID]);
  return <section className="settings-panel" aria-label="Remote Desktop session history"><div className="panel-heading"><h2>Session history</h2><span className="status-pill">{sessions.length} terminal · {events.length} live events</span></div>
    {historyError&&<p aria-live="polite">{historyError}</p>}<ol aria-label="Terminal Remote Desktop sessions">{sessions.map(session=><li key={session.session_id}><strong>{session.platform} · {session.state}</strong> · {new Date(session.terminated_at??session.requested_at).toLocaleString()}<br/><span>{Math.round(session.duration_ms/1000)}s · epoch {session.epoch_count} · {session.browser_to_agent_bytes+session.agent_to_browser_bytes} encrypted bytes · {session.permissions.join(", ")||"view only"}</span><br/><span>{guidance[session.termination_reason]??(session.termination_reason?"The session ended unexpectedly. Review endpoint and server health.":"Session ended.")}</span></li>)}</ol><button type="button" className="secondary" onClick={()=>void loadTerminal()}>Load older sessions</button>
    {error&&<p aria-live="polite">{error}</p>}<ol aria-label="Current Remote Desktop session events">{events.map(event=><li key={event.sequence}><strong>{event.event_type}</strong> · {event.actor_type} · {new Date(event.occurred_at).toLocaleString()}<br/><span>{guidance[event.reason_code]??(event.reason_code?"The session ended unexpectedly. Review endpoint and server health.":"Session metadata recorded.")}</span></li>)}</ol><button type="button" className="secondary" onClick={()=>void load()}>Load newer events</button>
  </section>
}
